version: '3'

services:
  jupyter:
    build: .
    image: clemon-jupyter:latest
    restart: always
    ports:
      - 8888:8888
    volumes:
      - ./work/:/home/jovyan/work/
    environment:
      - JUPYTER_ENABLE_LAB=yes