version: '3'

services:
  jupyterlab:
    image: jupyter/scipy-notebook:latest
    restart: always
    ports:
      - 8888
    volumes:
      - /home/clemon/work/:/home/clemon/work
    user: root
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - NB_USER=clemon
      - CHOWN_HOME=yes
      - GRANT_SUDO=yes
  caddy: 
    image: caddy
    restart: always
    depends_on:
      - jupyterlab
    ports:
      - 80:80
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
    